"""
SOC Incident Response Forensics Report Generator.
Exports detailed Markdown and HTML executive briefings for detected security incidents.
"""
from datetime import datetime
from typing import Dict, Any, List
import json

class IncidentReportGenerator:
    @staticmethod
    def generate_markdown_report(alert: Dict[str, Any], threat_intel: Dict[str, Any] = None) -> str:
        """Generates a professional SOC incident forensics report in Markdown."""
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

        evidence = alert.get("evidence_json", "[]")
        if isinstance(evidence, str):
            try:
                evidence_list = json.loads(evidence)
            except Exception:
                evidence_list = [evidence]
        else:
            evidence_list = evidence

        evidence_md = "\n".join(f"- `{log}`" for log in evidence_list[:15]) if evidence_list else "_No raw log evidence attached._"

        ti_section = ""
        if threat_intel and threat_intel.get("reputation") == "MALICIOUS":
            ti_section = f"""
### 🌐 Threat Intelligence Correlation
- **Reputation**: `MALICIOUS` (Confidence: {threat_intel.get('risk_score')}%)
- **Threat Actor**: {threat_intel.get('threat_actor')}
- **Classification**: {threat_intel.get('threat_type')}
- **Geo-Location**: {threat_intel.get('geo', {}).get('city')}, {threat_intel.get('geo', {}).get('country')} ({threat_intel.get('geo', {}).get('asn')} - {threat_intel.get('geo', {}).get('isp')})
- **IOC Tags**: `{", ".join(threat_intel.get('tags', []))}`
"""

        report = f"""# 🛡️ SOC INCIDENT FORENSIC REPORT: #{alert.get('id', 'N/A')}
**Generated By**: SOC Sentinel Automated SIEM Engine  
**Timestamp**: {now_str}  
**Classification**: TLP:AMBER (Internal Security Team Only)

---

## 1. Executive Summary
- **Incident Title**: {alert.get('title')}
- **Severity**: **{alert.get('severity')}**
- **Incident Status**: `{alert.get('status')}`
- **Source IP / Asset**: `{alert.get('source_ip', 'Unknown')}`
- **Target User / Host**: `{alert.get('user') or 'N/A'}` -> `{alert.get('dest_ip', 'Internal Host')}`
- **Total Related Events**: {alert.get('event_count', 1)}

## 2. Threat Classification & MITRE ATT&CK Mapping
- **Detection Rule**: `{alert.get('rule_name')}`
- **MITRE ATT&CK Tactic**: `{alert.get('mitre_tactic')}`
- **MITRE Technique**: `{alert.get('mitre_technique_id')} - {alert.get('mitre_technique_name')}`
- **Attack Vector**: {alert.get('description')}
{ti_section}
## 3. Forensic Evidence & Log Artifacts
The following telemetry records were correlated to produce this detection:

{evidence_md}

## 4. Recommended Containment & Remediation Playbook
{alert.get('recommended_action', 'Execute standard SOC containment procedures.')}

- [ ] **Step 1: Network Containment** - Enforce firewall perimeter drop rule on source IP.
- [ ] **Step 2: Identity Isolation** - Invalidate active session tokens and force credential rotation.
- [ ] **Step 3: Endpoint Triage** - Scan target host for secondary persistence mechanisms or web shells.
- [ ] **Step 4: Threat Intel Feed Update** - Propagate IOC to perimeter SIEM and EDR blocklists.

## 5. Analyst Review & Case Notes
- **Lead Investigator**: SOC Tier 2 Analyst
- **Analyst Notes**: {alert.get('analyst_notes') or 'Investigation initiated. Waiting for telemetry verification.'}
- **Disposition**: {alert.get('status')}

---
_CONFIDENTIAL - Generated by SOC Sentinel Incident Management Platform_
"""
        return report
